/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ShoesManager.GUI;

import ShoesManager.BUS.LoaiBUS;
import ShoesManager.BUS.MauSacBUS;
import ShoesManager.BUS.SanPhamBUS;
import ShoesManager.BUS.ThuongHieuBUS;
import ShoesManager.BUS.XuatXuBUS;
import ShoesManager.DTO.LoaiDTO;
import ShoesManager.DTO.MauSacDTO;
import ShoesManager.DTO.SanPhamDTO;
import ShoesManager.DTO.ThuongHieuDTO;
import ShoesManager.DTO.XuatXuDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HiamKaito
 */
public class ChonSanPham extends javax.swing.JDialog {

    /**
     * Creates new form ChonSanPham
     */
    public ChonSanPham(java.awt.Frame parent, boolean modal)  {
        super(parent, modal);
        this.setLocation(20, 20);
        try {
            init();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        initComponents();
      
        
        try {
            nhapThongTin_MaLoai();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nhapThongTin_MaXX();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nhapThongTin_MauSac();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nhapThongTin_MaThuongHieu();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nhapTimKiem_MaLoai();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nhapTimKiem_MaXX();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nhapTimKiem_MauSac();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nhapTimKiem_MaThuongHieu();
        } catch (Exception ex) {
            Logger.getLogger(ChonSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        // hiển thị các dữ liệu table
        actionButtondisplay();
    }
    
    private Color colorPanel_Top, colorPanel_Center, colorText;
    private SanPhamBUS list_SP;
   
    private DefaultTableModel model;
    
    
    public void init() throws Exception {
        colorPanel_Top = Memory.colorThemes;
        colorPanel_Center = Memory.colorThemes_2;
        colorText = Memory.colorText;
    
        list_SP = new SanPhamBUS();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCenter = new javax.swing.JPanel();
        pTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongTin = new javax.swing.JTable();
        pThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfMaGiay = new javax.swing.JTextField();
        tfTenGiay = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfGia = new javax.swing.JTextField();
        tfSize = new javax.swing.JTextField();
        tfDoiTuongSD = new javax.swing.JTextField();
        tfChatLieu = new javax.swing.JTextField();
        cbbThongtin_MaLoai = new javax.swing.JComboBox<>();
        cbbThongtin_MaXX = new javax.swing.JComboBox<>();
        cbbThongtin_MaMau = new javax.swing.JComboBox<>();
        cbbThongtin_MaThuongHieu = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        pTimKiem = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfTimKiem_TenGiay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbbTimKiem_MaLoai = new javax.swing.JComboBox<>();
        cbbTimKiem_MaXX = new javax.swing.JComboBox<>();
        cbbTimKiem_MaMau = new javax.swing.JComboBox<>();
        cbbTimKiem_MaThuongHieu = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        btnHuyTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pCenter.setBackground(colorPanel_Center);
        pCenter.setPreferredSize(new java.awt.Dimension(1280, 600));

        tblThongTin.setBackground(new java.awt.Color(204, 204, 204));
        tblThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Giày", "Tên Giày", "Số lượng", "Giá", "Size", "Đối Tượng sử dụng","Chất liệu","Mã Loại","Mã Xuất xứ","Mã màu","Mã thương hiệu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false,false,false,false,false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongTin.setGridColor(new java.awt.Color(102, 255, 102));
        tblThongTin.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblThongTin.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongTin);

        javax.swing.GroupLayout pTableLayout = new javax.swing.GroupLayout(pTable);
        pTable.setLayout(pTableLayout);
        pTableLayout.setHorizontalGroup(
            pTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pTableLayout.setVerticalGroup(
            pTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTableLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tên Giày");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mã Giày");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Số Lượng ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Giá");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Size");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Đối Tượng SD");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Chất Liệu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Mã Loại");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Mã Xuất Xứ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Mã Màu");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Mã Thương Hiệu");

        tfMaGiay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfMaGiay.setToolTipText("Không thể sửa Mã sản phẩm!!");
        tfMaGiay.setEnabled(false);
        tfMaGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaGiayActionPerformed(evt);
            }
        });

        tfTenGiay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTenGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenGiayActionPerformed(evt);
            }
        });

        tfSoLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSoLuong.setToolTipText("Không thể sửa Số lượng sản phẩm!!");
        tfSoLuong.setEnabled(false);
        tfSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoLuongActionPerformed(evt);
            }
        });

        tfGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGiaActionPerformed(evt);
            }
        });

        tfSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSizeActionPerformed(evt);
            }
        });

        tfDoiTuongSD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDoiTuongSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDoiTuongSDActionPerformed(evt);
            }
        });

        tfChatLieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChatLieuActionPerformed(evt);
            }
        });

        cbbThongtin_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbThongtin_MaLoai.setSelectedItem("selected");
        cbbThongtin_MaLoai.setName(""); // NOI18N
        cbbThongtin_MaLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbbThongtin_MaLoaiFocusLost(evt);
            }
        });

        cbbThongtin_MaXX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaXX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbThongtin_MaMau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbThongtin_MaThuongHieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setText("Chọn");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pThongTinLayout = new javax.swing.GroupLayout(pThongTin);
        pThongTin.setLayout(pThongTinLayout);
        pThongTinLayout.setHorizontalGroup(
            pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongTinLayout.createSequentialGroup()
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTenGiay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfMaGiay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfSize, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfChatLieu)
                                    .addComponent(cbbThongtin_MaLoai, 0, 118, Short.MAX_VALUE)
                                    .addComponent(cbbThongtin_MaXX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbbThongtin_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbThongtin_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfDoiTuongSD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pThongTinLayout.setVerticalGroup(
            pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfChatLieu)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbThongtin_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThongtin_MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThongtin_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThongtin_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDoiTuongSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Tên Giày");

        tfTimKiem_TenGiay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTimKiem_TenGiay.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Mã Loại");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Mã Xuất Xứ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Mã Màu");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Mã Thương Hiệu");

        cbbTimKiem_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTimKiem_MaXX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaXX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTimKiem_MaMau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTimKiem_MaThuongHieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        btnHuyTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuyTimKiem.setText("Hủy Tìm Kiếm");
        btnHuyTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyTimKiemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pTimKiemLayout = new javax.swing.GroupLayout(pTimKiem);
        pTimKiem.setLayout(pTimKiemLayout);
        pTimKiemLayout.setHorizontalGroup(
            pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTimKiemLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(tfTimKiem_TenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pTimKiemLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbTimKiem_MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTimKiem_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTimKiem_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTimKiem_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTimKiemLayout.createSequentialGroup()
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTimKiemLayout.createSequentialGroup()
                                .addComponent(btnHuyTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pTimKiemLayout.setVerticalGroup(
            pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimKiemLayout.createSequentialGroup()
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTimKiem_TenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnHuyTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbTimKiem_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTimKiem_MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addComponent(pThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinMouseClicked
        int  i=tblThongTin.getSelectedRow();

        tfMaGiay.setText(tblThongTin.getModel().getValueAt(i, 0).toString());
        tfTenGiay.setText(tblThongTin.getModel().getValueAt(i, 1).toString());
        tfSoLuong.setText(tblThongTin.getModel().getValueAt(i, 2).toString());
        tfGia.setText(tblThongTin.getModel().getValueAt(i, 3).toString());
        tfSize.setText(tblThongTin.getModel().getValueAt(i, 4).toString());
        tfDoiTuongSD.setText(tblThongTin.getModel().getValueAt(i, 5).toString());
        tfChatLieu.setText(tblThongTin.getModel().getValueAt(i, 6).toString());
        cbbThongtin_MaLoai.setSelectedItem(tblThongTin.getModel().getValueAt(i, 7));
        cbbThongtin_MaXX.setSelectedItem(tblThongTin.getModel().getValueAt(i, 8));
        cbbThongtin_MaMau.setSelectedItem(tblThongTin.getModel().getValueAt(i, 9));
        cbbThongtin_MaThuongHieu.setSelectedItem(tblThongTin.getModel().getValueAt(i, 10));

        // không cho thêm
        tfMaGiay.setEditable(false);
        tfMaGiay.setEnabled(false);
        tfSoLuong.setEditable(false);
    }//GEN-LAST:event_tblThongTinMouseClicked

    private void tfMaGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaGiayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaGiayActionPerformed

    private void tfTenGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenGiayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenGiayActionPerformed

    private void tfSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoLuongActionPerformed

    private void tfGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGiaActionPerformed

    private void tfSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSizeActionPerformed

    private void tfDoiTuongSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDoiTuongSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDoiTuongSDActionPerformed

    private void tfChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChatLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChatLieuActionPerformed

    private void cbbThongtin_MaLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbbThongtin_MaLoaiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThongtin_MaLoaiFocusLost

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked

    }//GEN-LAST:event_btnThemMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        Memory.maSP = tfMaGiay.getText();
        this.dispose();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        try {
            // TODO add your handling code here:
            list_SP.docDB();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!tfTimKiem_TenGiay.getText().equals(""))
        list_SP.setList_SP( list_SP.timKiem_TenGiay(tfTimKiem_TenGiay.getText()) );
        if (!cbbTimKiem_MaLoai.getSelectedItem().equals("--Select--"))
        list_SP.setList_SP( list_SP.timKiem_MaLoai((String) cbbTimKiem_MaLoai.getSelectedItem()) );
        if (!cbbTimKiem_MaXX.getSelectedItem().equals("--Select--"))
        list_SP.setList_SP( list_SP.timKiem_MaXX((String) cbbTimKiem_MaXX.getSelectedItem()) );
        if (!cbbTimKiem_MaMau.getSelectedItem().equals("--Select--"))
        list_SP.setList_SP( list_SP.timKiem_MaMau((String) cbbTimKiem_MaMau.getSelectedItem()) );
        if (!cbbTimKiem_MaThuongHieu.getSelectedItem().equals("--Select--"))
        list_SP.setList_SP( list_SP.timKiem_MaThuongHieu((String) cbbTimKiem_MaThuongHieu.getSelectedItem()) );

        actionButtondisplay();
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void btnHuyTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyTimKiemMouseClicked
        try {
            list_SP = new SanPhamBUS();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            list_SP.docDB();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfTimKiem_TenGiay.setText("");
        cbbTimKiem_MaLoai.setSelectedIndex(0);
        cbbTimKiem_MaXX.setSelectedIndex(0);
        cbbTimKiem_MaMau.setSelectedIndex(0);
        cbbTimKiem_MaThuongHieu.setSelectedIndex(0);
        actionButtondisplay();
    }//GEN-LAST:event_btnHuyTimKiemMouseClicked

    private void createVectorHeader() {
        if (model.getRowCount()==0) {
            Vector<String> header = new Vector();
            header.add("Mã Giày");
            header.add("Tên Giày");
            header.add("Số lượng");
            header.add("Giá");
            header.add("Size");
            header.add("Đối tượng sd");
            header.add("Chất liệu");
            header.add("Mã Loại");
            header.add("Mã Xuất Xứ");
            header.add("Mã Màu");
            header.add("Mã Thương hiệu");
            
            model = new DefaultTableModel(header, 0){
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };;
        }
    }
    
    private void actionButtondisplay() {
        model = new DefaultTableModel();
        
        createVectorHeader();
        for (int i=0 ; i < list_SP.getNumbSanPham(); i++) {
            SanPhamDTO sp = new SanPhamDTO();
            
            sp = list_SP.getInfor(i);
            
            createVectorHeader();
            
            Vector row=new Vector();
            row.add(sp.getStrMaGiay());
            row.add(sp.getStrTenGiay());
            row.add(sp.getiSoLuong());
            row.add(sp.getiGia());
            row.add(sp.getiSize());
            row.add(sp.getStrDoiTuongSD());
            row.add(sp.getStrChatLieu());
            row.add(sp.getStrMaLoai());
            row.add(sp.getStrMaxx());
            row.add(sp.getStrMaMau());
            row.add(sp.getStrMaThuongHieu());
            
            model.addRow(row);
        }
       
        
        tblThongTin.setModel(model);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChonSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChonSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChonSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChonSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChonSanPham dialog = new ChonSanPham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyTimKiem;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbbThongtin_MaLoai;
    private javax.swing.JComboBox<String> cbbThongtin_MaMau;
    private javax.swing.JComboBox<String> cbbThongtin_MaThuongHieu;
    private javax.swing.JComboBox<String> cbbThongtin_MaXX;
    private javax.swing.JComboBox<String> cbbTimKiem_MaLoai;
    private javax.swing.JComboBox<String> cbbTimKiem_MaMau;
    private javax.swing.JComboBox<String> cbbTimKiem_MaThuongHieu;
    private javax.swing.JComboBox<String> cbbTimKiem_MaXX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pTable;
    private javax.swing.JPanel pThongTin;
    private javax.swing.JPanel pTimKiem;
    private javax.swing.JTable tblThongTin;
    private javax.swing.JTextField tfChatLieu;
    private javax.swing.JTextField tfDoiTuongSD;
    private javax.swing.JTextField tfGia;
    private javax.swing.JTextField tfMaGiay;
    private javax.swing.JTextField tfSize;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenGiay;
    private javax.swing.JTextField tfTimKiem_TenGiay;
    // End of variables declaration//GEN-END:variables

/**
     * Combobox Thông Tin
     */
    public void nhapThongTin_MaLoai() throws Exception{
        LoaiBUS bus =new LoaiBUS();
        ArrayList<LoaiDTO> arr =bus.getList_Loai();
        String[] s = new String[bus.getNumbLoai()+1];
        s[0]="--Select--";
        int i = 1;
        for (LoaiDTO dto : arr) {
            
            s[i] = dto.getStrMaloai();
            i++;
           
        }
        cbbThongtin_MaLoai.setModel(new DefaultComboBoxModel<>(s));
    }

    public void nhapThongTin_MaXX() throws Exception{
        XuatXuBUS xx =new XuatXuBUS();
        ArrayList<XuatXuDTO> arr =xx.getList_XuatXu();
        String[] s = new String[xx.getNumbXuatXu()+1];
        s[0]="--Select--";
        int i = 1;
        for (XuatXuDTO dto : arr) {
            s[i] = dto.getStrMaxuatxu();
            i++;
           
        }
        cbbThongtin_MaXX.setModel(new DefaultComboBoxModel<>(s));
    }
    
    public void nhapThongTin_MauSac() throws Exception{
        MauSacBUS ms =new MauSacBUS();
        ArrayList<MauSacDTO> arr =ms.getList_MauSac();
        String[] s = new String[ms.getNumbMauSac()+1];
        s[0]="--Select--";
        int i = 1;
        for (MauSacDTO dto : arr) {
            s[i] = dto.getStrMamau();
            i++;
           
        }
        cbbThongtin_MaMau.setModel(new DefaultComboBoxModel<>(s));
    }
    public void nhapThongTin_MaThuongHieu() throws Exception{
        ThuongHieuBUS th =new ThuongHieuBUS();
        ArrayList<ThuongHieuDTO> arr =th.getList_ThuongHieu();
        String[] s = new String[th.getNumbThuongHieu()+1];
        s[0]="--Select--";
        int i = 1;
        for (ThuongHieuDTO dto : arr) {
            s[i] = dto.getStrMathuonghieu();
            i++;
           
        }
        cbbThongtin_MaThuongHieu.setModel(new DefaultComboBoxModel<>(s));
    }
    /**
     * Combobox Tìm Kiếm
     */
    public void nhapTimKiem_MaLoai() throws Exception{
        LoaiBUS bus =new LoaiBUS();
        ArrayList<LoaiDTO> arr =bus.getList_Loai();
        String[] s = new String[bus.getNumbLoai()+1];
        s[0]="--Select--";
        int i = 1;
        for (LoaiDTO dto : arr) {
            s[i] = dto.getStrMaloai();
            i++;
           
        }
        cbbTimKiem_MaLoai.setModel(new DefaultComboBoxModel<>(s));
    }

    public void nhapTimKiem_MaXX() throws Exception{
        XuatXuBUS xx =new XuatXuBUS();
        ArrayList<XuatXuDTO> arr =xx.getList_XuatXu();
        String[] s = new String[xx.getNumbXuatXu()+1];
        s[0]="--Select--";
        int i = 1;
        for (XuatXuDTO dto : arr) {
            s[i] = dto.getStrMaxuatxu();
            i++;
           
        }
        cbbTimKiem_MaXX.setModel(new DefaultComboBoxModel<>(s));
    }
    
    public void nhapTimKiem_MauSac() throws Exception{
        MauSacBUS ms =new MauSacBUS();
        ArrayList<MauSacDTO> arr =ms.getList_MauSac();
        String[] s = new String[ms.getNumbMauSac()+1];
        s[0]="--Select--";
        int i = 1;
        for (MauSacDTO dto : arr) {
            s[i] = dto.getStrMamau();
            i++;
           
        }
        cbbTimKiem_MaMau.setModel(new DefaultComboBoxModel<>(s));
    }
    public void nhapTimKiem_MaThuongHieu() throws Exception{
        ThuongHieuBUS th =new ThuongHieuBUS();
        ArrayList<ThuongHieuDTO> arr =th.getList_ThuongHieu();
        String[] s = new String[th.getNumbThuongHieu()+1];
        s[0]="--Select--";
        int i = 1;
        for (ThuongHieuDTO dto : arr) {
            s[i] = dto.getStrMathuonghieu();
            i++;
           
        }
        cbbTimKiem_MaThuongHieu.setModel(new DefaultComboBoxModel<>(s));
    }
}
