package ShoesManager.GUI;
import ShoesManager.BUS.LoaiBUS;
import ShoesManager.BUS.MauSacBUS;
import ShoesManager.BUS.XuatXuBUS;
import ShoesManager.BUS.SanPhamBUS;
import ShoesManager.BUS.ThuongHieuBUS;
import ShoesManager.DTO.LoaiDTO;
import ShoesManager.DTO.MauSacDTO;
import ShoesManager.DTO.SanPhamDTO;
import ShoesManager.DTO.ThuongHieuDTO;
import ShoesManager.DTO.XuatXuDTO;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Sanpham extends javax.swing.JFrame  implements MouseListener {

    public Sanpham() throws Exception {
        this.setUndecorated(true);

        init();
        initComponents();
        
        
        // các hàm xử lý sau khi vào
        kiemTraCapBac();
        colordefault();
        // hiển thị cbb
        nhapThongTin_MaLoai();
        nhapThongTin_MaXX();
        nhapThongTin_MauSac();
        nhapThongTin_MaThuongHieu();
        nhapTimKiem_MaLoai();
        nhapTimKiem_MaXX();
        nhapTimKiem_MauSac();
        nhapTimKiem_MaThuongHieu();
        
        // hiển thị các dữ liệu table
        actionButtondisplay();
//        actionButtondisplayChiTiet();
        if (!Memory.flag_Menu) {
            pTop.setVisible(false);
            menuThanhCongcu.setText("Hiện thanh công cụ");
        }
        
      
    }
    
    private Color colorPanel_Top, colorPanel_Center, colorText;
    private JLabel[] listLblTop;
    private String[] strArr_Top;
    private SanPhamBUS list_SP;
   
    private DefaultTableModel model;
    
    
    public void init() throws Exception {
        colorPanel_Top = Memory.colorThemes;
        colorPanel_Center = Memory.colorThemes_2;
        colorText = Memory.colorText;
        
        list_SP = new SanPhamBUS();
        
        strArr_Top = new String[10];
        strArr_Top[0] = "Hóa đơn";
        strArr_Top[1] = "Khuyến mãi";
        strArr_Top[2] = "Nhập hàng";
        strArr_Top[3] = "Hàng hóa";
        strArr_Top[4] = "Thống kê";
        strArr_Top[5] = "Excel";
        strArr_Top[6] = "Trở về";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_MauNen = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        pTop = createPanel_LblTop(strArr_Top);
        pCenter = new javax.swing.JPanel();
        pTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongTin = new javax.swing.JTable();
        pThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfMaGiay = new javax.swing.JTextField();
        tfTenGiay = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfGia = new javax.swing.JTextField();
        tfSize = new javax.swing.JTextField();
        tfDoiTuongSD = new javax.swing.JTextField();
        tfChatLieu = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        cbbThongtin_MaLoai = new javax.swing.JComboBox<>();
        cbbThongtin_MaXX = new javax.swing.JComboBox<>();
        cbbThongtin_MaMau = new javax.swing.JComboBox<>();
        cbbThongtin_MaThuongHieu = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pTimKiem = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfTimKiem_TenGiay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbbTimKiem_MaLoai = new javax.swing.JComboBox<>();
        cbbTimKiem_MaXX = new javax.swing.JComboBox<>();
        cbbTimKiem_MaMau = new javax.swing.JComboBox<>();
        cbbTimKiem_MaThuongHieu = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        btnHuyTimKiem = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        menuTaiKhoan = new javax.swing.JMenu();
        menuTaiKhoan_ThongTin = new javax.swing.JMenuItem();
        menuTaiKhoan_DangXuat = new javax.swing.JMenuItem();
        menuThanhCongcu = new javax.swing.JMenu();
        MenuMauNen = new javax.swing.JMenu();
        rdbtnThongTin_MauCam = new javax.swing.JRadioButtonMenuItem();
        rdbtnThongTin_MauDen = new javax.swing.JRadioButtonMenuItem();
        rdbtnThongTin_Mautrang = new javax.swing.JRadioButtonMenuItem();
        menuTroVe = new javax.swing.JMenu();
        menuThoat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pTop.setBackground(colorPanel_Top);
        pTop.setPreferredSize(new java.awt.Dimension(1280, 70));
        getContentPane().add(pTop, java.awt.BorderLayout.NORTH);

        pCenter.setBackground(colorPanel_Center);
        pCenter.setPreferredSize(new java.awt.Dimension(1280, 600));

        pTable.setBackground(colorPanel_Center);

        tblThongTin.setBackground(new java.awt.Color(204, 204, 204));
        tblThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Giày", "Tên Giày", "Số lượng", "Giá", "Size", "Đối Tượng sử dụng","Chất liệu","Mã Loại","Mã Xuất xứ","Mã màu","Mã thương hiệu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
                , java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false,false,false,false,false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongTin.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblThongTin.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongTin);
        tblThongTin.setAutoCreateRowSorter(true);

        javax.swing.GroupLayout pTableLayout = new javax.swing.GroupLayout(pTable);
        pTable.setLayout(pTableLayout);
        pTableLayout.setHorizontalGroup(
            pTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pTableLayout.setVerticalGroup(
            pTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );

        pThongTin.setBackground(colorPanel_Center);
        pThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel1.setBackground(colorPanel_Center);
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(colorText);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tên Giày");

        jLabel2.setBackground(colorPanel_Center);
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(colorText);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mã Giày");

        jLabel3.setBackground(colorPanel_Center);
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(colorText);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Số Lượng ");

        jLabel4.setBackground(colorPanel_Center);
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(colorText);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Giá");

        jLabel5.setBackground(colorPanel_Center);
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(colorText);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Size");

        jLabel6.setBackground(colorPanel_Center);
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(colorText);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Đối Tượng SD");

        jLabel7.setBackground(colorPanel_Center);
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(colorText);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Chất Liệu");

        jLabel8.setBackground(colorPanel_Center);
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(colorText);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Mã Loại");

        jLabel9.setBackground(colorPanel_Center);
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(colorText);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Mã Xuất Xứ");

        jLabel10.setBackground(colorPanel_Center);
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(colorText);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Mã Màu");

        jLabel11.setBackground(colorPanel_Center);
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(colorText);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Mã Thương Hiệu");

        tfMaGiay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfMaGiay.setToolTipText("Không thể sửa Mã sản phẩm!!");
        tfMaGiay.setEnabled(false);
        tfMaGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaGiayActionPerformed(evt);
            }
        });

        tfTenGiay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTenGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenGiayActionPerformed(evt);
            }
        });

        tfSoLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSoLuong.setToolTipText("Không thể sửa Số lượng sản phẩm!!");
        tfSoLuong.setEnabled(false);
        tfSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoLuongActionPerformed(evt);
            }
        });

        tfGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGiaActionPerformed(evt);
            }
        });

        tfSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSizeActionPerformed(evt);
            }
        });

        tfDoiTuongSD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDoiTuongSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDoiTuongSDActionPerformed(evt);
            }
        });

        tfChatLieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChatLieuActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setEnabled(false);
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        cbbThongtin_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbThongtin_MaLoai.setSelectedItem("selected");
        cbbThongtin_MaLoai.setName(""); // NOI18N
        cbbThongtin_MaLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbbThongtin_MaLoaiFocusLost(evt);
            }
        });

        cbbThongtin_MaXX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaXX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbThongtin_MaMau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbThongtin_MaThuongHieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbThongtin_MaThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLuu.setText("LƯU");
        btnLuu.setEnabled(false);
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setEnabled(false);
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pThongTinLayout = new javax.swing.GroupLayout(pThongTin);
        pThongTin.setLayout(pThongTinLayout);
        pThongTinLayout.setHorizontalGroup(
            pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongTinLayout.createSequentialGroup()
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTenGiay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfMaGiay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfSize, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfChatLieu)
                                    .addComponent(cbbThongtin_MaLoai, 0, 118, Short.MAX_VALUE)
                                    .addComponent(cbbThongtin_MaXX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addComponent(cbbThongtin_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                            .addGroup(pThongTinLayout.createSequentialGroup()
                                .addComponent(cbbThongtin_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(tfDoiTuongSD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pThongTinLayout.setVerticalGroup(
            pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfChatLieu)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbThongtin_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThongtin_MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThongtin_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThongtin_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDoiTuongSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pTimKiem.setBackground(colorPanel_Center);
        pTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel13.setBackground(colorPanel_Center);
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(colorText);
        jLabel13.setText("Tên Giày");

        tfTimKiem_TenGiay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTimKiem_TenGiay.setToolTipText("");

        jLabel19.setBackground(colorPanel_Center);
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(colorText);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Mã Loại");

        jLabel20.setBackground(colorPanel_Center);
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(colorText);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Mã Xuất Xứ");

        jLabel21.setBackground(colorPanel_Center);
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(colorText);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Mã Màu");

        jLabel22.setBackground(colorPanel_Center);
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(colorText);
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Mã Thương Hiệu");

        cbbTimKiem_MaLoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTimKiem_MaXX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaXX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTimKiem_MaMau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTimKiem_MaThuongHieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTimKiem_MaThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        btnHuyTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuyTimKiem.setText("Hủy Tìm Kiếm");
        btnHuyTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyTimKiemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pTimKiemLayout = new javax.swing.GroupLayout(pTimKiem);
        pTimKiem.setLayout(pTimKiemLayout);
        pTimKiemLayout.setHorizontalGroup(
            pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTimKiemLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(tfTimKiem_TenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pTimKiemLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbTimKiem_MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTimKiem_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTimKiem_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbTimKiem_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTimKiemLayout.createSequentialGroup()
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTimKiemLayout.createSequentialGroup()
                                .addComponent(btnHuyTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pTimKiemLayout.setVerticalGroup(
            pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimKiemLayout.createSequentialGroup()
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTimKiem_TenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnHuyTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pTimKiemLayout.createSequentialGroup()
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbTimKiem_MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTimKiem_MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem_MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbTimKiem_MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addComponent(pThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(pCenter, java.awt.BorderLayout.CENTER);

        menuTaiKhoan.setText("Tài khoản");

        menuTaiKhoan_ThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShoesManager/images/user.png"))); // NOI18N
        menuTaiKhoan_ThongTin.setText("Thông tin");
        menuTaiKhoan_ThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuTaiKhoan_ThongTinMouseReleased(evt);
            }
        });
        menuTaiKhoan.add(menuTaiKhoan_ThongTin);

        menuTaiKhoan_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShoesManager/images/logout.png"))); // NOI18N
        menuTaiKhoan_DangXuat.setText("Đăng xuất");
        menuTaiKhoan_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuTaiKhoan_DangXuatMouseReleased(evt);
            }
        });
        menuTaiKhoan.add(menuTaiKhoan_DangXuat);

        menubar.add(menuTaiKhoan);

        menuThanhCongcu.setText("Ẩn thanh công cụ");
        menuThanhCongcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThanhCongcuMouseClicked(evt);
            }
        });
        menubar.add(menuThanhCongcu);

        MenuMauNen.setText("Màu nền");

        buttonGroup_MauNen.add(rdbtnThongTin_MauCam);
        rdbtnThongTin_MauCam.setSelected(true);
        rdbtnThongTin_MauCam.setText("Màu cam/ trắng");
        rdbtnThongTin_MauCam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rdbtnThongTin_MauCamMouseReleased(evt);
            }
        });
        rdbtnThongTin_MauCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnThongTin_MauCamActionPerformed(evt);
            }
        });
        MenuMauNen.add(rdbtnThongTin_MauCam);

        buttonGroup_MauNen.add(rdbtnThongTin_MauDen);
        rdbtnThongTin_MauDen.setText("Màu đen/ đen");
        rdbtnThongTin_MauDen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rdbtnThongTin_MauDenMouseReleased(evt);
            }
        });
        rdbtnThongTin_MauDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnThongTin_MauDenActionPerformed(evt);
            }
        });
        MenuMauNen.add(rdbtnThongTin_MauDen);

        buttonGroup_MauNen.add(rdbtnThongTin_Mautrang);
        rdbtnThongTin_Mautrang.setText("Màu trắng/ xanh");
        rdbtnThongTin_Mautrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rdbtnThongTin_MautrangMouseReleased(evt);
            }
        });
        rdbtnThongTin_Mautrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnThongTin_MautrangActionPerformed(evt);
            }
        });
        MenuMauNen.add(rdbtnThongTin_Mautrang);

        menubar.add(MenuMauNen);

        menuTroVe.setText("Trở về");
        menuTroVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTroVeMouseClicked(evt);
            }
        });
        menubar.add(menuTroVe);

        menuThoat.setText("Thoát");
        menuThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThoatMouseClicked(evt);
            }
        });
        menubar.add(menuThoat);

        setJMenuBar(menubar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
  
    
    private void tblThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinMouseClicked
        int  i=tblThongTin.getSelectedRow();
          
          tfMaGiay.setText(tblThongTin.getModel().getValueAt(i, 0).toString());
          tfTenGiay.setText(tblThongTin.getModel().getValueAt(i, 1).toString());
          tfSoLuong.setText(tblThongTin.getModel().getValueAt(i, 2).toString());
          tfGia.setText(tblThongTin.getModel().getValueAt(i, 3).toString());
          tfSize.setText(tblThongTin.getModel().getValueAt(i, 4).toString());
          tfDoiTuongSD.setText(tblThongTin.getModel().getValueAt(i, 5).toString());
          tfChatLieu.setText(tblThongTin.getModel().getValueAt(i, 6).toString());
          cbbThongtin_MaLoai.setSelectedItem(tblThongTin.getModel().getValueAt(i, 7));
          cbbThongtin_MaXX.setSelectedItem(tblThongTin.getModel().getValueAt(i, 8));
          cbbThongtin_MaMau.setSelectedItem(tblThongTin.getModel().getValueAt(i, 9));
          cbbThongtin_MaThuongHieu.setSelectedItem(tblThongTin.getModel().getValueAt(i, 10));
  
        // không cho thêm
        tfMaGiay.setEditable(false);
        tfMaGiay.setEnabled(false);
        tfSoLuong.setEditable(false);
        btnSua.setEnabled(true);
        btnThem.setEnabled(false);
        btnLuu.setEnabled(false);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_tblThongTinMouseClicked

    private void rdbtnThongTin_MautrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnThongTin_MautrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnThongTin_MautrangActionPerformed

    private void rdbtnThongTin_MauDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnThongTin_MauDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnThongTin_MauDenActionPerformed

    private void rdbtnThongTin_MauCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnThongTin_MauCamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnThongTin_MauCamActionPerformed

    private void rdbtnThongTin_MauCamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnThongTin_MauCamMouseReleased
        Memory.colorThemes =  new Color(250, 160, 100);
        Memory.colorThemes_2 = new Color(255, 255, 255);
        Memory.colorText = new Color(0, 0, 0);
        colorPanel_Top = Memory.colorThemes;
        colorPanel_Center = Memory.colorThemes_2;
        colorText = Memory.colorText;
        setTextColor("đen");
        System.out.println("da thay doi mau nen thanh cam trang");        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnThongTin_MauCamMouseReleased

    private void rdbtnThongTin_MauDenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnThongTin_MauDenMouseReleased
        // TODO add your handling code here:
        Memory.colorThemes =  new Color(0, 0, 0);
        Memory.colorThemes_2 = new Color(0, 0, 0);
        Memory.colorText = new Color(255, 255, 255);
        colorPanel_Top = Memory.colorThemes;
        colorPanel_Center = Memory.colorThemes_2;
        colorText = Memory.colorText;
        setTextColor("trắng");
        System.out.println("da thay doi mau nen thanh den");
    }//GEN-LAST:event_rdbtnThongTin_MauDenMouseReleased

    private void rdbtnThongTin_MautrangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbtnThongTin_MautrangMouseReleased
        // TODO add your handling code here:
        Memory.colorThemes =  new Color(255, 255, 255);
        Memory.colorThemes_2 = new Color(131,189,246);
        Memory.colorText = new Color(0, 0, 0);
        colorPanel_Top = Memory.colorThemes;
        colorPanel_Center = Memory.colorThemes_2;
        colorText = Memory.colorText;
        setTextColor("đen");
        System.out.println("da thay doi mau nen thanh trang");
    }//GEN-LAST:event_rdbtnThongTin_MautrangMouseReleased

    private void menuThanhCongcuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThanhCongcuMouseClicked
        // TODO add your handling code here:
        if ( Memory.flag_Menu ) {
            pTop.setVisible(false);
            menuThanhCongcu.setText("Hiện thanh công cụ");
            Memory.flag_Menu = false;
        }
        else {
            pTop.setVisible(true);
            menuThanhCongcu.setText("Ẩn thanh công cụ");
            Memory.flag_Menu = true;
        }
    }//GEN-LAST:event_menuThanhCongcuMouseClicked

    private void menuTroVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTroVeMouseClicked
        // TODO add your handling code here:
        Home home;
        try {
            home = new Home();
            home.setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi");
        }
    }//GEN-LAST:event_menuTroVeMouseClicked

    private void menuTaiKhoan_ThongTinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTaiKhoan_ThongTinMouseReleased

        // TODO add your handling code here:
        UserInfor ui = new UserInfor();
        ui.setVisible(true);
    }//GEN-LAST:event_menuTaiKhoan_ThongTinMouseReleased

    private void menuTaiKhoan_DangXuatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTaiKhoan_DangXuatMouseReleased
        // TODO add your handling code here:
        Login lg;
        try {
            lg = new Login();
            lg.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuTaiKhoan_DangXuatMouseReleased

    private void menuThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThoatMouseClicked
        // TODO add your handling code here:
        Question_YesNO Q = new Question_YesNO("Bạn có muốn thoát không?");
        Q.setVisible(true);
        
    }//GEN-LAST:event_menuThoatMouseClicked

    private void tfMaGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaGiayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaGiayActionPerformed

    private void tfTenGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenGiayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenGiayActionPerformed

    private void tfSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoLuongActionPerformed

    private void tfGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGiaActionPerformed

    private void tfSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSizeActionPerformed

    private void tfDoiTuongSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDoiTuongSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDoiTuongSDActionPerformed

    private void tfChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChatLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChatLieuActionPerformed

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        

    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        try {
            // TODO add your handling code here:
            list_SP.docDB();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (!tfTimKiem_TenGiay.getText().equals(""))
            list_SP.setList_SP( list_SP.timKiem_TenGiay(tfTimKiem_TenGiay.getText()) );
        if (!cbbTimKiem_MaLoai.getSelectedItem().equals("--Select--"))
            list_SP.setList_SP( list_SP.timKiem_MaLoai((String) cbbTimKiem_MaLoai.getSelectedItem()) );
        if (!cbbTimKiem_MaXX.getSelectedItem().equals("--Select--"))
            list_SP.setList_SP( list_SP.timKiem_MaXX((String) cbbTimKiem_MaXX.getSelectedItem()) );
        if (!cbbTimKiem_MaMau.getSelectedItem().equals("--Select--"))
            list_SP.setList_SP( list_SP.timKiem_MaMau((String) cbbTimKiem_MaMau.getSelectedItem()) );
        if (!cbbTimKiem_MaThuongHieu.getSelectedItem().equals("--Select--"))
            list_SP.setList_SP( list_SP.timKiem_MaThuongHieu((String) cbbTimKiem_MaThuongHieu.getSelectedItem()) );
        
        actionButtondisplay();
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void cbbThongtin_MaLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbbThongtin_MaLoaiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbThongtin_MaLoaiFocusLost

    private void btnHuyTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyTimKiemMouseClicked
        try {
            list_SP = new SanPhamBUS();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            list_SP.docDB();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfTimKiem_TenGiay.setText("");
        cbbTimKiem_MaLoai.setSelectedIndex(0);
        cbbTimKiem_MaXX.setSelectedIndex(0);
        cbbTimKiem_MaMau.setSelectedIndex(0);
        cbbTimKiem_MaThuongHieu.setSelectedIndex(0);
        actionButtondisplay();
    }//GEN-LAST:event_btnHuyTimKiemMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
   
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked

    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        tfSoLuong.setEnabled(true);
          tfSoLuong.setEditable(true);
          
          tfMaGiay.setText(list_SP.getDefaultMaHD());
          tfTenGiay.setText("");
          tfSoLuong.setText("");
          tfGia.setText("");
          tfSize.setText("");
          tfDoiTuongSD.setText("");
          tfChatLieu.setText("");
          cbbThongtin_MaLoai.setSelectedIndex(0);
          cbbThongtin_MaXX.setSelectedIndex(0);
          cbbThongtin_MaMau.setSelectedIndex(0);
          cbbThongtin_MaThuongHieu.setSelectedIndex(0);
          tfTenGiay.requestFocus();
          btnThem.setEnabled(false);
          btnLuu.setEnabled(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn sửa chứ!!");  
        if(a==JOptionPane.YES_OPTION){  
            
        SanPhamDTO sp=new SanPhamDTO();
        sp.setStrMaGiay(tfMaGiay.getText());
        sp.setStrTenGiay(tfTenGiay.getText());
        sp.setiSoLuong(Integer.parseInt(tfSoLuong.getText()));
        sp.setiGia(Integer.parseInt(tfGia.getText()));
        sp.setiSize(Integer.parseInt(tfSize.getText()));
        sp.setStrDoiTuongSD(tfDoiTuongSD.getText());
        sp.setStrChatLieu(tfChatLieu.getText());
        sp.setStrMaLoai((String) cbbThongtin_MaLoai.getSelectedItem());
        sp.setStrMaxx((String) cbbThongtin_MaXX.getSelectedItem());
        sp.setStrMaMau((String) cbbThongtin_MaMau.getSelectedItem());
        sp.setStrMaThuongHieu((String) cbbThongtin_MaThuongHieu.getSelectedItem());
        
        if(cbbThongtin_MaLoai.getSelectedItem()=="--Select--" || cbbThongtin_MaMau.getSelectedItem()=="--Select--"
                || cbbThongtin_MaXX.getSelectedItem()=="--Select--" || cbbThongtin_MaThuongHieu.getSelectedItem()=="--Select--")
        {
            JOptionPane.showMessageDialog(null, "Sửa không thành công, vui lòng chọn hết các thông tin!","Alert",JOptionPane.ERROR_MESSAGE);
        
        }else{
        try {
            list_SP.sua(sp);
        } catch (Exception ex) {
            Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            list_SP.docDB();
        } catch (Exception ex) {
            Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        JOptionPane.showMessageDialog(null, "Sửa thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);
            actionButtondisplay();
        }
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfMaGiay.setText("");
        tfTenGiay.setText("");
        tfSoLuong.setText("");
        tfGia.setText("");
        tfSize.setText("");
        tfDoiTuongSD.setText("");
        tfChatLieu.setText("");
        cbbThongtin_MaLoai.setSelectedIndex(0);
        cbbThongtin_MaXX.setSelectedIndex(0);
        cbbThongtin_MaMau.setSelectedIndex(0);
        cbbThongtin_MaThuongHieu.setSelectedIndex(0);
        tfTenGiay.requestFocus();
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnThem.setEnabled(true);
        btnLuu.setEnabled(false);
        tblThongTin.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn lưu chứ!!");  
                 if(a==JOptionPane.YES_OPTION){  
                SanPhamDTO sp = new SanPhamDTO();
                sp.setStrMaGiay(tfMaGiay.getText());
                sp.setStrTenGiay(tfTenGiay.getText());
                if (tfGia.getText().equals(""))
                tfGia.setText("0");
                sp.setiGia(Integer.parseInt(tfGia.getText()));
                if (tfSize.getText().equals(""))
                tfSize.setText("0");
                sp.setiSize(Integer.parseInt(tfSize.getText()));
                if (tfSoLuong.getText().equals(""))
                tfSoLuong.setText("0");
                sp.setiSoLuong(Integer.parseInt(tfSoLuong.getText()));
                sp.setStrChatLieu(tfChatLieu.getText());
                sp.setStrDoiTuongSD(tfDoiTuongSD.getText());
                sp.setStrMaLoai((String)cbbThongtin_MaLoai.getSelectedItem());
                sp.setStrMaxx((String)cbbThongtin_MaXX.getSelectedItem());
                sp.setStrMaMau((String)cbbThongtin_MaMau.getSelectedItem());
                sp.setStrMaThuongHieu((String)cbbThongtin_MaThuongHieu.getSelectedItem());
                if(cbbThongtin_MaLoai.getSelectedItem()=="--Select--" || cbbThongtin_MaMau.getSelectedItem()=="--Select--"
                || cbbThongtin_MaXX.getSelectedItem()=="--Select--" || cbbThongtin_MaThuongHieu.getSelectedItem()=="--Select--"
                || tfTenGiay.getText()=="" || tfDoiTuongSD.getText()=="" ||tfChatLieu.getText()==""||tfGia.getText()=="" 
                ||tfSize.getText()=="" || tfSoLuong.getText()=="")
                {
                JOptionPane.showMessageDialog(null, "Lưu không thành công, vui lòng nhập hết các thông tin!","Alert",JOptionPane.ERROR_MESSAGE);
        
                }else{
                try {
                    list_SP.them(sp);
                } catch (Exception ex) {
                    Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    list_SP.docDB();
                } catch (Exception ex) {
                    Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
                }
        JOptionPane.showMessageDialog(null, "Lưu thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);        
        actionButtondisplay();
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa chứ!!");  
        if(a==JOptionPane.YES_OPTION){  
        SanPhamDTO sp = new SanPhamDTO();
        sp.setStrMaGiay(tfMaGiay.getText());
        
        try {
            list_SP.xoa(sp);
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            list_SP.docDB();
        } catch (Exception ex) {
            Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Xóa thành công!", "Success", JOptionPane.INFORMATION_MESSAGE); 
        actionButtondisplay();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    int x_Mouse, y_Mouse;
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x_Mouse = evt.getX();
         y_Mouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        setLocation(x - x_Mouse, y - y_Mouse);
    }//GEN-LAST:event_formMouseDragged
    /**
     * Combobox Thông Tin
     */
    public void nhapThongTin_MaLoai() throws Exception{
        LoaiBUS bus =new LoaiBUS();
        ArrayList<LoaiDTO> arr =bus.getList_Loai();
        String[] s = new String[bus.getNumbLoai()+1];
        s[0]="--Select--";
        int i = 1;
        for (LoaiDTO dto : arr) {
            
            s[i] = dto.getStrMaloai();
            i++;
           
        }
        cbbThongtin_MaLoai.setModel(new DefaultComboBoxModel<>(s));
    }

    public void nhapThongTin_MaXX() throws Exception{
        XuatXuBUS xx =new XuatXuBUS();
        ArrayList<XuatXuDTO> arr =xx.getList_XuatXu();
        String[] s = new String[xx.getNumbXuatXu()+1];
        s[0]="--Select--";
        int i = 1;
        for (XuatXuDTO dto : arr) {
            s[i] = dto.getStrMaxuatxu();
            i++;
           
        }
        cbbThongtin_MaXX.setModel(new DefaultComboBoxModel<>(s));
    }
    
    public void nhapThongTin_MauSac() throws Exception{
        MauSacBUS ms =new MauSacBUS();
        ArrayList<MauSacDTO> arr =ms.getList_MauSac();
        String[] s = new String[ms.getNumbMauSac()+1];
        s[0]="--Select--";
        int i = 1;
        for (MauSacDTO dto : arr) {
            s[i] = dto.getStrMamau();
            i++;
           
        }
        cbbThongtin_MaMau.setModel(new DefaultComboBoxModel<>(s));
    }
    public void nhapThongTin_MaThuongHieu() throws Exception{
        ThuongHieuBUS th =new ThuongHieuBUS();
        ArrayList<ThuongHieuDTO> arr =th.getList_ThuongHieu();
        String[] s = new String[th.getNumbThuongHieu()+1];
        s[0]="--Select--";
        int i = 1;
        for (ThuongHieuDTO dto : arr) {
            s[i] = dto.getStrMathuonghieu();
            i++;
           
        }
        cbbThongtin_MaThuongHieu.setModel(new DefaultComboBoxModel<>(s));
    }
    /**
     * Combobox Tìm Kiếm
     */
    public void nhapTimKiem_MaLoai() throws Exception{
        LoaiBUS bus =new LoaiBUS();
        ArrayList<LoaiDTO> arr =bus.getList_Loai();
        String[] s = new String[bus.getNumbLoai()+1];
        s[0]="--Select--";
        int i = 1;
        for (LoaiDTO dto : arr) {
            s[i] = dto.getStrMaloai();
            i++;
           
        }
        cbbTimKiem_MaLoai.setModel(new DefaultComboBoxModel<>(s));
    }

    public void nhapTimKiem_MaXX() throws Exception{
        XuatXuBUS xx =new XuatXuBUS();
        ArrayList<XuatXuDTO> arr =xx.getList_XuatXu();
        String[] s = new String[xx.getNumbXuatXu()+1];
        s[0]="--Select--";
        int i = 1;
        for (XuatXuDTO dto : arr) {
            s[i] = dto.getStrMaxuatxu();
            i++;
           
        }
        cbbTimKiem_MaXX.setModel(new DefaultComboBoxModel<>(s));
    }
    
    public void nhapTimKiem_MauSac() throws Exception{
        MauSacBUS ms =new MauSacBUS();
        ArrayList<MauSacDTO> arr =ms.getList_MauSac();
        String[] s = new String[ms.getNumbMauSac()+1];
        s[0]="--Select--";
        int i = 1;
        for (MauSacDTO dto : arr) {
            s[i] = dto.getStrMamau();
            i++;
           
        }
        cbbTimKiem_MaMau.setModel(new DefaultComboBoxModel<>(s));
    }
    public void nhapTimKiem_MaThuongHieu() throws Exception{
        ThuongHieuBUS th =new ThuongHieuBUS();
        ArrayList<ThuongHieuDTO> arr =th.getList_ThuongHieu();
        String[] s = new String[th.getNumbThuongHieu()+1];
        s[0]="--Select--";
        int i = 1;
        for (ThuongHieuDTO dto : arr) {
            s[i] = dto.getStrMathuonghieu();
            i++;
           
        }
        cbbTimKiem_MaThuongHieu.setModel(new DefaultComboBoxModel<>(s));
    }
    
    /**
     * Hàm kiểm tra xem cập bậc của nó 
     * 1 : Admin FULL POWER
     * 2 : Nhập xuất file Excel và Thống Kê
     * 3 : Kiểm tra hàng hóa
     * 4 : Nhập Hàng
     * 5 : Khuyến mãi
     * 6 : Hóa đơn
     */
    public void kiemTraCapBac(){
        // truyền tham số cấp bậc chức vụ vào
        int iKey = Memory.iCapBac;
        
        if ( iKey != 1) {
            for (int i  = 0 ; i < strArr_Top.length ; i++) {
                listLblTop[i].setVisible(false);
            }
        }
        
        switch (iKey) {
            case 2:
                listLblTop[6].setVisible(true);
                listLblTop[5].setVisible(true);
                listLblTop[4].setVisible(true);
                break;
            case 3:
                listLblTop[6].setVisible(true);
                listLblTop[3].setVisible(true);
                break;
            case 4:
                listLblTop[6].setVisible(true);
                listLblTop[2].setVisible(true);
                break;
            case 5:
                listLblTop[6].setVisible(true);
                listLblTop[1].setVisible(true);
                break;
            case 6:
                listLblTop[6].setVisible(true);
                listLblTop[0].setVisible(true);
                break;
        }
    }
    
    private void createVectorHeader() {
        if (model.getRowCount()==0) {
            Vector<String> header = new Vector();
            header.add("Mã Giày");
            header.add("Tên Giày");
            header.add("Số lượng");
            header.add("Giá");
            header.add("Size");
            header.add("Đối tượng sd");
            header.add("Chất liệu");
            header.add("Mã Loại");
            header.add("Mã Xuất Xứ");
            header.add("Mã Màu");
            header.add("Mã Thương hiệu");
            
            model = new DefaultTableModel(header, 0){
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }
            };;
        }
    }
    
    private void actionButtondisplay() {
        model = new DefaultTableModel();
        
        createVectorHeader();
        for (int i=0 ; i < list_SP.getNumbSanPham(); i++) {
            SanPhamDTO sp = new SanPhamDTO();
            
            sp = list_SP.getInfor(i);
            
            createVectorHeader();
            
            Vector row=new Vector();
            row.add(sp.getStrMaGiay());
            row.add(sp.getStrTenGiay());
            row.add(sp.getiSoLuong());
            row.add(sp.getiGia());
            row.add(sp.getiSize());
            row.add(sp.getStrDoiTuongSD());
            row.add(sp.getStrChatLieu());
            row.add(sp.getStrMaLoai());
            row.add(sp.getStrMaxx());
            row.add(sp.getStrMaMau());
            row.add(sp.getStrMaThuongHieu());
            
            model.addRow(row);
        }
       
        
        tblThongTin.setModel(model);
        
    }
 
    
    private JPanel createPanel_LblTop(String[] strArr_Top) {
        JPanel Panel = new JPanel();
        listLblTop = new JLabel[10];
        
        Panel.setLayout(new FlowLayout(0,30,10));
        Panel.setBackground(colorPanel_Top);
        
        for (int i=0 ; i < strArr_Top.length ; i++) {
            listLblTop[i] = new JLabel(new ImageIcon("./src/ShoesManager/images/Button Menu/150_50/"+strArr_Top[i]+".png"));
            listLblTop[i].setName(strArr_Top[i]);
            listLblTop[i].setOpaque(true);
            listLblTop[i].addMouseListener(this);
            listLblTop[i].setBackground(colorPanel_Top);
            
            Panel.add(listLblTop[i]);
        }
        
        return Panel;
    }
    
    public void setTextColor(String Mau){
          jLabel1.setForeground(colorText);
          jLabel2.setForeground(colorText);
          jLabel3.setForeground(colorText);
          jLabel4.setForeground(colorText);
          jLabel5.setForeground(colorText);
          jLabel6.setForeground(colorText);
          jLabel7.setForeground(colorText);
          jLabel8.setForeground(colorText);
          jLabel9.setForeground(colorText);
          jLabel10.setForeground(colorText);
          jLabel11.setForeground(colorText);
          jLabel13.setForeground(colorText);
          jLabel19.setForeground(colorText);
          jLabel20.setForeground(colorText);
          jLabel21.setForeground(colorText);
          jLabel22.setForeground(colorText);
         
          tfMaGiay.setForeground(colorText);
          tfMaGiay.setBackground(colorPanel_Center);
          tfTenGiay.setForeground(colorText);
          tfTenGiay.setBackground(colorPanel_Center);
          tfSoLuong.setForeground(colorText);
          tfSoLuong.setBackground(colorPanel_Center);
          tfGia.setForeground(colorText);
          tfGia.setBackground(colorPanel_Center);
          tfSize.setForeground(colorText);
          tfSize.setBackground(colorPanel_Center);
          tfDoiTuongSD.setForeground(colorText);
          tfDoiTuongSD.setBackground(colorPanel_Center);
          tfChatLieu.setForeground(colorText);
          tfChatLieu.setBackground(colorPanel_Center);
          tfTimKiem_TenGiay.setForeground(colorText);
          tfTimKiem_TenGiay.setBackground(colorPanel_Center);
          
        //-----------------------Đổi màu cho Panel
        pTop.setBackground( colorPanel_Top );
        pCenter.setBackground( colorPanel_Center );
        pTable.setBackground( colorPanel_Center );
        pThongTin.setBackground(colorPanel_Center);
        pTimKiem.setBackground(colorPanel_Center);
        //---------------------list lbl top
        for (int i=0 ; i < strArr_Top.length ; i++) {
            listLblTop[i].setBackground( colorPanel_Top );
        }
        
        jScrollPane2.setBackground(colorPanel_Center);
    }   
    
    public void colordefault(){
        Color color;
        color = new Color(250, 160, 100);
        if (Memory.colorThemes.getRGB() == color.getRGB() )
            rdbtnThongTin_MauCam.setSelected(true);
        color = new Color(0, 0, 0);
        if (Memory.colorThemes.getRGB() == color.getRGB() )
            rdbtnThongTin_MauDen.setSelected(true);
        color = new Color(255, 255, 255);
        if (Memory.colorThemes.getRGB() == color.getRGB() )
            rdbtnThongTin_Mautrang.setSelected(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Sanpham().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Sanpham.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuMauNen;
    private javax.swing.JButton btnHuyTimKiem;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup_MauNen;
    private javax.swing.JComboBox<String> cbbThongtin_MaLoai;
    private javax.swing.JComboBox<String> cbbThongtin_MaMau;
    private javax.swing.JComboBox<String> cbbThongtin_MaThuongHieu;
    private javax.swing.JComboBox<String> cbbThongtin_MaXX;
    private javax.swing.JComboBox<String> cbbTimKiem_MaLoai;
    private javax.swing.JComboBox<String> cbbTimKiem_MaMau;
    private javax.swing.JComboBox<String> cbbTimKiem_MaThuongHieu;
    private javax.swing.JComboBox<String> cbbTimKiem_MaXX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuTaiKhoan;
    private javax.swing.JMenuItem menuTaiKhoan_DangXuat;
    private javax.swing.JMenuItem menuTaiKhoan_ThongTin;
    private javax.swing.JMenu menuThanhCongcu;
    private javax.swing.JMenu menuThoat;
    private javax.swing.JMenu menuTroVe;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pTable;
    private javax.swing.JPanel pThongTin;
    private javax.swing.JPanel pTimKiem;
    private javax.swing.JPanel pTop;
    private javax.swing.JRadioButtonMenuItem rdbtnThongTin_MauCam;
    private javax.swing.JRadioButtonMenuItem rdbtnThongTin_MauDen;
    private javax.swing.JRadioButtonMenuItem rdbtnThongTin_Mautrang;
    private javax.swing.JTable tblThongTin;
    private javax.swing.JTextField tfChatLieu;
    private javax.swing.JTextField tfDoiTuongSD;
    private javax.swing.JTextField tfGia;
    private javax.swing.JTextField tfMaGiay;
    private javax.swing.JTextField tfSize;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenGiay;
    private javax.swing.JTextField tfTimKiem_TenGiay;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void mouseClicked(MouseEvent me) {
        JLabel src = (JLabel) me.getSource();
        System.out.println(src.getName() + "is Clicked");
        
    }

    @Override
    public void mousePressed(MouseEvent me) {
        JLabel src = (JLabel) me.getSource();
        System.out.println(src.getName() + "is Pressed");
        src.setIcon(new ImageIcon("./src/ShoesManager/images/Button Menu/150_50/"+src.getName()+" click.png"));
         
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        JLabel src = (JLabel) me.getSource();
        System.out.println(src.getName() + "is Entered");
        src.setIcon(new ImageIcon("./src/ShoesManager/images/Button Menu/150_50/"+src.getName()+" hover.png"));
    
        // xử lý nút trở về
        if ( src.getName().equals("Trở về") ) {
            Home home;
            try {
                home = new Home();
                home.setVisible(true);
                setVisible(false);
            } catch (Exception e) {
                System.out.println("Lỗi");
            }
        }
        
          
        if ( src.getName().equals("Khuyến mãi") ) 
                try {
                    KhuyenMai dm;
                    dm = new KhuyenMai();
                    dm.setVisible(true);
                    setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                } 
        
        if ( src.getName().equals("Nhập hàng") ) 
                try {
                    PhieuNhap hd = new PhieuNhap();
                    hd.setVisible(true);
                    setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        if ( src.getName().equals("Hóa đơn") ) 
                try {
                    HoaDon hd;
                    hd = new HoaDon();
                    hd.setVisible(true);
                    setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        if ( src.getName().equals("Thống kê") ) 
                try {
                    ThongKe hd;
                    hd = new ThongKe();
                    hd.setVisible(true);
                    setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        if ( src.getName().equals("Excel") ) 
                try {
                    Excel hd;
                    hd = new Excel();
                    hd.setVisible(true);
                    setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        JLabel src = (JLabel) me.getSource();
        System.out.println(src.getName() + "is Entered");
        src.setIcon(new ImageIcon("./src/ShoesManager/images/Button Menu/150_50/"+src.getName()+" hover.png"));
           
    }

    @Override
    public void mouseExited(MouseEvent me) {
        JLabel src = (JLabel) me.getSource();
        System.out.println(src.getName() + "is Exited");
        src.setIcon(new ImageIcon("./src/ShoesManager/images/Button Menu/150_50/"+src.getName()+".png"));
         
    }
}
